version: "3.9"

services:
  app:
    build: .
    container_name: golang-app
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "4000:4001"
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - WITHDRAW_URL=http://your-withdraw-api
      - DATABASE_URL=postgres://user:pass@postgres:5432/dbname?sslmode=disable
    volumes:
      - .:/app
    working_dir: /app

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
