version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golang-app
    env_file:
      - .env
    depends_on:
      - rabbitmq
    ports:
      - "4000:4001"
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      GIN_MODE: release         # ลด overhead logging
    volumes:
      - .:/app
      - /go/pkg/mod             # cache module
    working_dir: /app
    command: >
      sh -c "go mod tidy && go run main.go"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP protocol
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbit tcp_listeners [{\"0.0.0.0\",5672}]"
      RABBITMQ_VM_MEMORY_HIGH_WATERMARK: 0.4     # ใช้ RAM แค่ 40%
      RABBITMQ_DISK_FREE_LIMIT: 50MB
      RABBITMQ_HEARTBEAT: 60
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
