version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  app:
    build: .
    container_name: golang-app
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "4000:4001"
    volumes:
      - .:/app
    working_dir: /app
    command: ["./wait-for-rabbitmq.sh", "rabbitmq", "go", "run", "main.go"]

volumes:
  rabbitmq_data:
